### ISSUE TITLE
I can't use my hand to break wood, dirt & gravel

### ISSUE THREAD

**Issue by cyberpunkbln** [SlimeKnights/HarvestTweaks#5]
Hello,

i can't use my hand to break wood, dirt & gravel. I have not made changes in the original generated config. Is that a feature? I mean you have wrote that no gameplay changes will be made if harvest level installed?

I love your mod for tweaking the difficulty:).

When it is a feature how can i harvest wood, dirt and so on?

greets

Edit: In your description you wrote: You can and all are set at the first start to the standard values.

**Comment by bonii-xx** [comment]
Hm, that should not be. Might be a bug.

**Comment by DarkCorvuz** [comment]
edit : i'm sorry i thought i saw a flaw in the code but i'm rusty so i don't know for sure

i think somewhere down the line the code might be pointing to the fact a tool is needed for breaking those blocks and thus :
    // we require a tool, but no fitting tool is present. we prevent any breaking
event.setCanceled(true);
this happens

i set a wooden shovel to harvest lvl -1 just for testing and then i could mine dirt and clay and gravel and grass
but not wood because it requires an axe
so somewhere it tells your mod to use the correct tool where you should be able to mine it even without a tool

just trying to help you out in figuring this out :s

**Comment by The-Arcanian** [comment]
I am having the same problem. I cannot dig minecraft:log or minecraft:grass with my fists, even if I remove their entries from the config file, but I can with the appropriate wood tool. I did not test other materials but I bet its the same.

I am using the recommended Forge version of 12.18.3.2185.

**Comment by The-Arcanian** [comment]
Ok, weird... I just deleted the config and reinstalled mod and now it I can dig them with my fist, but I never touched their config entree last time until it did not work...

**Comment by Dukat863** [comment]
This happened to me when I removed a block from another mod. I deleted the configuration files and it worked. So I compared them - the only difference is that there were mentions of a removed block.
I added a line "minecraft:nonexistent_block"=0 to Blocks.cfg in Blocks/Pickaxe and voila, grass and trees won't break anymore.
Apparently, instead of ignoring an improper line mod just ceases to work.

**Comment by WesCook** [comment]
This also affects leaves.  With an invalid config file shears can no longer harvest leaves.

I don't know how I'm going to find the line(s) at fault though.  It's a pretty gigantic file.

**Comment by bonii-xx** [comment]
Fixed with 961018638aeb27e122457c0ea5ffbd72f83d4a56

>I don't know how I'm going to find the line(s) at fault though. It's a pretty gigantic file.

Looking into the log where there's an error telling you exactly which entry it is. :package:

**Comment by WesCook** [comment]
Oh...  Well that's also a pretty gigantic file.

I ended up just running a diff between a good copy and my bad one and found the broken lines.  Super glad to see this fixed though, as it'll make updates a lot smoother.  Thanks bonbon!
